// Copyright (c) 2010 Satoshi Nakamoto
// Copyright (c) 2009-2017 The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <base58.h>
#include <bill.h>
#include <gramscale.h>
#include <house.h>
#include <oracle.h>
#include <pool.h>
#include <note.h>
#include <bmmcache.h>
#include <chain.h>
#include <clientversion.h>
#include <core_io.h>
#include <crypto/ripemd160.h>
#include <consensus/merkle.h>
#include <consensus/validation.h>
#include <init.h>
#include <l1client.h>
#include <miner.h>
#include <mainchainaddress.h>
#include <validation.h>
#include <httpserver.h>
#include <net.h>
#include <netbase.h>
#include <rpc/blockchain.h>
#include <rpc/server.h>
#include <rpc/util.h>
#include <sidechain.h>
#include <sidechainclient.h>
#include <timedata.h>
#include <txdb.h>
#include <util.h>
#include <validationinterface.h>
#include <utilstrencodings.h>
#ifdef ENABLE_WALLET
#include <wallet/rpcwallet.h>
#include <wallet/wallet.h>
#include <wallet/walletdb.h>
#endif
#include <warnings.h>

#include <stdint.h>

#include <chrono>
#include <deque>
#include <memory>
#include <mutex>
#ifdef HAVE_MALLOC_INFO
#include <malloc.h>
#endif

#include <univalue.h>

UniValue validateaddress(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "validateaddress \"address\"\n"
            "\nReturn information about the given bitcoin address.\n"
            "DEPRECATION WARNING: Parts of this command have been deprecated and moved to getaddressinfo. Clients must\n"
            "transition to using getaddressinfo to access this information before upgrading to v0.18. The following deprecated\n"
            "fields have moved to getaddressinfo and will only be shown here with -deprecatedrpc=validateaddress: ismine, iswatchonly,\n"
            "script, hex, pubkeys, sigsrequired, pubkey, addresses, embedded, iscompressed, account, timestamp, hdkeypath, kdmasterkeyid.\n"
            "\nArguments:\n"
            "1. \"address\"                    (string, required) The bitcoin address to validate\n"
            "\nResult:\n"
            "{\n"
            "  \"isvalid\" : true|false,       (boolean) If the address is valid or not. If not, this is the only property returned.\n"
            "  \"address\" : \"address\",        (string) The bitcoin address validated\n"
            "  \"scriptPubKey\" : \"hex\",       (string) The hex encoded scriptPubKey generated by the address\n"
            "  \"isscript\" : true|false,      (boolean) If the key is a script\n"
            "  \"iswitness\" : true|false,     (boolean) If the address is a witness address\n"
            "  \"witness_version\" : version   (numeric, optional) The version number of the witness program\n"
            "  \"witness_program\" : \"hex\"     (string, optional) The hex value of the witness program\n"
            "}\n"
            "\nExamples:\n"
            + HelpExampleCli("validateaddress", "\"1PSSGeFHDnKNxiEyFrD1wcEaHr9hrQDDWc\"")
            + HelpExampleRpc("validateaddress", "\"1PSSGeFHDnKNxiEyFrD1wcEaHr9hrQDDWc\"")
        );

    CTxDestination dest = DecodeDestination(request.params[0].get_str());
    bool isValid = IsValidDestination(dest);

    UniValue ret(UniValue::VOBJ);
    ret.pushKV("isvalid", isValid);
    if (isValid)
    {

#ifdef ENABLE_WALLET
        if (!::vpwallets.empty() && IsDeprecatedRPCEnabled("validateaddress")) {
            ret.pushKVs(getaddressinfo(request));
        }
#endif
        if (ret["address"].isNull()) {
            std::string currentAddress = EncodeDestination(dest);
            ret.pushKV("address", currentAddress);

            CScript scriptPubKey = GetScriptForDestination(dest);
            ret.pushKV("scriptPubKey", HexStr(scriptPubKey.begin(), scriptPubKey.end()));;

            UniValue detail = DescribeAddress(dest);
            ret.pushKVs(detail);
        }
    }
    return ret;
}

// Needed even with !ENABLE_WALLET, to pass (ignored) pointers around
class CWallet;

UniValue createmultisig(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() < 2 || request.params.size() > 2)
    {
        std::string msg = "createmultisig nrequired [\"key\",...]\n"
            "\nCreates a multi-signature address with n signature of m keys required.\n"
            "It returns a json object with the address and redeemScript.\n"
            "\nArguments:\n"
            "1. nrequired                    (numeric, required) The number of required signatures out of the n keys.\n"
            "2. \"keys\"                       (string, required) A json array of hex-encoded public keys\n"
            "     [\n"
            "       \"key\"                    (string) The hex-encoded public key\n"
            "       ,...\n"
            "     ]\n"

            "\nResult:\n"
            "{\n"
            "  \"address\":\"multisigaddress\",  (string) The value of the new multisig address.\n"
            "  \"redeemScript\":\"script\"       (string) The string value of the hex-encoded redemption script.\n"
            "}\n"

            "\nExamples:\n"
            "\nCreate a multisig address from 2 public keys\n"
            + HelpExampleCli("createmultisig", "2 \"[\\\"03789ed0bb717d88f7d321a368d905e7430207ebbd82bd342cf11ae157a7ace5fd\\\",\\\"03dbc6764b8884a92e871274b87583e6d5c2a58819473e17e107ef3f6aa5a61626\\\"]\"") +
            "\nAs a json rpc call\n"
            + HelpExampleRpc("createmultisig", "2, \"[\\\"03789ed0bb717d88f7d321a368d905e7430207ebbd82bd342cf11ae157a7ace5fd\\\",\\\"03dbc6764b8884a92e871274b87583e6d5c2a58819473e17e107ef3f6aa5a61626\\\"]\"")
        ;
        throw std::runtime_error(msg);
    }

    int required = request.params[0].get_int();

    // Get the public keys
    const UniValue& keys = request.params[1].get_array();
    std::vector<CPubKey> pubkeys;
    for (unsigned int i = 0; i < keys.size(); ++i) {
        if (IsHex(keys[i].get_str()) && (keys[i].get_str().length() == 66 || keys[i].get_str().length() == 130)) {
            pubkeys.push_back(HexToPubKey(keys[i].get_str()));
        } else {
            throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, strprintf("Invalid public key: %s\nNote that from v0.16, createmultisig no longer accepts addresses."
            " Users must use addmultisigaddress to create multisig addresses with addresses known to the wallet.", keys[i].get_str()));
        }
    }

    // Construct using pay-to-script-hash:
    CScript inner = CreateMultisigRedeemscript(required, pubkeys);
    CScriptID innerID(inner);

    UniValue result(UniValue::VOBJ);
    result.pushKV("address", EncodeDestination(innerID));
    result.pushKV("redeemScript", HexStr(inner.begin(), inner.end()));

    return result;
}

UniValue verifymessage(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 3)
        throw std::runtime_error(
            "verifymessage \"address\" \"signature\" \"message\"\n"
            "\nVerify a signed message\n"
            "\nArguments:\n"
            "1. \"address\"         (string, required) The bitcoin address to use for the signature.\n"
            "2. \"signature\"       (string, required) The signature provided by the signer in base 64 encoding (see signmessage).\n"
            "3. \"message\"         (string, required) The message that was signed.\n"
            "\nResult:\n"
            "true|false   (boolean) If the signature is verified or not.\n"
            "\nExamples:\n"
            "\nUnlock the wallet for 30 seconds\n"
            + HelpExampleCli("walletpassphrase", "\"mypassphrase\" 30") +
            "\nCreate the signature\n"
            + HelpExampleCli("signmessage", "\"1D1ZrZNe3JUo7ZycKEYQQiQAWd9y54F4XX\" \"my message\"") +
            "\nVerify the signature\n"
            + HelpExampleCli("verifymessage", "\"1D1ZrZNe3JUo7ZycKEYQQiQAWd9y54F4XX\" \"signature\" \"my message\"") +
            "\nAs json rpc\n"
            + HelpExampleRpc("verifymessage", "\"1D1ZrZNe3JUo7ZycKEYQQiQAWd9y54F4XX\", \"signature\", \"my message\"")
        );

    LOCK(cs_main);

    std::string strAddress  = request.params[0].get_str();
    std::string strSign     = request.params[1].get_str();
    std::string strMessage  = request.params[2].get_str();

    CTxDestination destination = DecodeDestination(strAddress);
    if (!IsValidDestination(destination)) {
        throw JSONRPCError(RPC_TYPE_ERROR, "Invalid address");
    }

    const CKeyID *keyID = boost::get<CKeyID>(&destination);
    if (!keyID) {
        throw JSONRPCError(RPC_TYPE_ERROR, "Address does not refer to key");
    }

    bool fInvalid = false;
    std::vector<unsigned char> vchSig = DecodeBase64(strSign.c_str(), &fInvalid);

    if (fInvalid)
        throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, "Malformed base64 encoding");

    CHashWriter ss(SER_GETHASH, 0);
    ss << strMessageMagic;
    ss << strMessage;

    CPubKey pubkey;
    if (!pubkey.RecoverCompact(ss.GetHash(), vchSig))
        return false;

    return (pubkey.GetID() == *keyID);
}

UniValue signmessagewithprivkey(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 2)
        throw std::runtime_error(
            "signmessagewithprivkey \"privkey\" \"message\"\n"
            "\nSign a message with the private key of an address\n"
            "\nArguments:\n"
            "1. \"privkey\"         (string, required) The private key to sign the message with.\n"
            "2. \"message\"         (string, required) The message to create a signature of.\n"
            "\nResult:\n"
            "\"signature\"          (string) The signature of the message encoded in base 64\n"
            "\nExamples:\n"
            "\nCreate the signature\n"
            + HelpExampleCli("signmessagewithprivkey", "\"privkey\" \"my message\"") +
            "\nVerify the signature\n"
            + HelpExampleCli("verifymessage", "\"1D1ZrZNe3JUo7ZycKEYQQiQAWd9y54F4XX\" \"signature\" \"my message\"") +
            "\nAs json rpc\n"
            + HelpExampleRpc("signmessagewithprivkey", "\"privkey\", \"my message\"")
        );

    std::string strPrivkey = request.params[0].get_str();
    std::string strMessage = request.params[1].get_str();

    CBitcoinSecret vchSecret;
    bool fGood = vchSecret.SetString(strPrivkey);
    if (!fGood)
        throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, "Invalid private key");
    CKey key = vchSecret.GetKey();
    if (!key.IsValid())
        throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, "Private key outside allowed range");

    CHashWriter ss(SER_GETHASH, 0);
    ss << strMessageMagic;
    ss << strMessage;

    std::vector<unsigned char> vchSig;
    if (!key.SignCompact(ss.GetHash(), vchSig))
        throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, "Sign failed");

    return EncodeBase64(vchSig.data(), vchSig.size());
}

UniValue setmocktime(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "setmocktime timestamp\n"
            "\nSet the local time to given timestamp (-regtest only)\n"
            "\nArguments:\n"
            "1. timestamp  (integer, required) Unix seconds-since-epoch timestamp\n"
            "   Pass 0 to go back to using the system time."
        );

    if (!Params().MineBlocksOnDemand())
        throw std::runtime_error("setmocktime for regression testing (-regtest mode) only");

    // For now, don't change mocktime if we're in the middle of validation, as
    // this could have an effect on mempool time-based eviction, as well as
    // IsCurrentForFeeEstimation() and IsInitialBlockDownload().
    // TODO: figure out the right way to synchronize around mocktime, and
    // ensure all call sites of GetTime() are accessing this safely.
    LOCK(cs_main);

    RPCTypeCheck(request.params, {UniValue::VNUM});
    SetMockTime(request.params[0].get_int64());

    return NullUniValue;
}

static UniValue RPCLockedMemoryInfo()
{
    LockedPool::Stats stats = LockedPoolManager::Instance().stats();
    UniValue obj(UniValue::VOBJ);
    obj.pushKV("used", uint64_t(stats.used));
    obj.pushKV("free", uint64_t(stats.free));
    obj.pushKV("total", uint64_t(stats.total));
    obj.pushKV("locked", uint64_t(stats.locked));
    obj.pushKV("chunks_used", uint64_t(stats.chunks_used));
    obj.pushKV("chunks_free", uint64_t(stats.chunks_free));
    return obj;
}

#ifdef HAVE_MALLOC_INFO
static std::string RPCMallocInfo()
{
    char *ptr = nullptr;
    size_t size = 0;
    FILE *f = open_memstream(&ptr, &size);
    if (f) {
        malloc_info(0, f);
        fclose(f);
        if (ptr) {
            std::string rv(ptr, size);
            free(ptr);
            return rv;
        }
    }
    return "";
}
#endif

UniValue getmemoryinfo(const JSONRPCRequest& request)
{
    /* Please, avoid using the word "pool" here in the RPC interface or help,
     * as users will undoubtedly confuse it with the other "memory pool"
     */
    if (request.fHelp || request.params.size() > 1)
        throw std::runtime_error(
            "getmemoryinfo (\"mode\")\n"
            "Returns an object containing information about memory usage.\n"
            "Arguments:\n"
            "1. \"mode\" determines what kind of information is returned. This argument is optional, the default mode is \"stats\".\n"
            "  - \"stats\" returns general statistics about memory usage in the daemon.\n"
            "  - \"mallocinfo\" returns an XML string describing low-level heap state (only available if compiled with glibc 2.10+).\n"
            "\nResult (mode \"stats\"):\n"
            "{\n"
            "  \"locked\": {               (json object) Information about locked memory manager\n"
            "    \"used\": xxxxx,          (numeric) Number of bytes used\n"
            "    \"free\": xxxxx,          (numeric) Number of bytes available in current arenas\n"
            "    \"total\": xxxxxxx,       (numeric) Total number of bytes managed\n"
            "    \"locked\": xxxxxx,       (numeric) Amount of bytes that succeeded locking. If this number is smaller than total, locking pages failed at some point and key data could be swapped to disk.\n"
            "    \"chunks_used\": xxxxx,   (numeric) Number allocated chunks\n"
            "    \"chunks_free\": xxxxx,   (numeric) Number unused chunks\n"
            "  }\n"
            "}\n"
            "\nResult (mode \"mallocinfo\"):\n"
            "\"<malloc version=\"1\">...\"\n"
            "\nExamples:\n"
            + HelpExampleCli("getmemoryinfo", "")
            + HelpExampleRpc("getmemoryinfo", "")
        );

    std::string mode = request.params[0].isNull() ? "stats" : request.params[0].get_str();
    if (mode == "stats") {
        UniValue obj(UniValue::VOBJ);
        obj.pushKV("locked", RPCLockedMemoryInfo());
        return obj;
    } else if (mode == "mallocinfo") {
#ifdef HAVE_MALLOC_INFO
        return RPCMallocInfo();
#else
        throw JSONRPCError(RPC_INVALID_PARAMETER, "mallocinfo is only available when compiled with glibc 2.10+");
#endif
    } else {
        throw JSONRPCError(RPC_INVALID_PARAMETER, "unknown mode " + mode);
    }
}

uint32_t getCategoryMask(UniValue cats) {
    cats = cats.get_array();
    uint32_t mask = 0;
    for (unsigned int i = 0; i < cats.size(); ++i) {
        uint32_t flag = 0;
        std::string cat = cats[i].get_str();
        if (!GetLogCategory(&flag, &cat)) {
            throw JSONRPCError(RPC_INVALID_PARAMETER, "unknown logging category " + cat);
        }
        if (flag == BCLog::NONE) {
            return 0;
        }
        mask |= flag;
    }
    return mask;
}

UniValue logging(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() > 2) {
        throw std::runtime_error(
            "logging ( <include> <exclude> )\n"
            "Gets and sets the logging configuration.\n"
            "When called without an argument, returns the list of categories with status that are currently being debug logged or not.\n"
            "When called with arguments, adds or removes categories from debug logging and return the lists above.\n"
            "The arguments are evaluated in order \"include\", \"exclude\".\n"
            "If an item is both included and excluded, it will thus end up being excluded.\n"
            "The valid logging categories are: " + ListLogCategories() + "\n"
            "In addition, the following are available as category names with special meanings:\n"
            "  - \"all\",  \"1\" : represent all logging categories.\n"
            "  - \"none\", \"0\" : even if other logging categories are specified, ignore all of them.\n"
            "\nArguments:\n"
            "1. \"include\"        (array of strings, optional) A json array of categories to add debug logging\n"
            "     [\n"
            "       \"category\"   (string) the valid logging category\n"
            "       ,...\n"
            "     ]\n"
            "2. \"exclude\"        (array of strings, optional) A json array of categories to remove debug logging\n"
            "     [\n"
            "       \"category\"   (string) the valid logging category\n"
            "       ,...\n"
            "     ]\n"
            "\nResult:\n"
            "{                   (json object where keys are the logging categories, and values indicates its status\n"
            "  \"category\": 0|1,  (numeric) if being debug logged or not. 0:inactive, 1:active\n"
            "  ...\n"
            "}\n"
            "\nExamples:\n"
            + HelpExampleCli("logging", "\"[\\\"all\\\"]\" \"[\\\"http\\\"]\"")
            + HelpExampleRpc("logging", "[\"all\"], \"[libevent]\"")
        );
    }

    uint32_t originalLogCategories = logCategories;
    if (request.params[0].isArray()) {
        logCategories |= getCategoryMask(request.params[0]);
    }

    if (request.params[1].isArray()) {
        logCategories &= ~getCategoryMask(request.params[1]);
    }

    // Update libevent logging if BCLog::LIBEVENT has changed.
    // If the library version doesn't allow it, UpdateHTTPServerLogging() returns false,
    // in which case we should clear the BCLog::LIBEVENT flag.
    // Throw an error if the user has explicitly asked to change only the libevent
    // flag and it failed.
    uint32_t changedLogCategories = originalLogCategories ^ logCategories;
    if (changedLogCategories & BCLog::LIBEVENT) {
        if (!UpdateHTTPServerLogging(logCategories & BCLog::LIBEVENT)) {
            logCategories &= ~BCLog::LIBEVENT;
            if (changedLogCategories == BCLog::LIBEVENT) {
            throw JSONRPCError(RPC_INVALID_PARAMETER, "libevent logging cannot be updated when using libevent before v2.1.1.");
            }
        }
    }

    UniValue result(UniValue::VOBJ);
    std::vector<CLogCategoryActive> vLogCatActive = ListActiveLogCategories();
    for (const auto& logCatActive : vLogCatActive) {
        result.pushKV(logCatActive.category, logCatActive.active);
    }

    return result;
}

UniValue echo(const JSONRPCRequest& request)
{
    if (request.fHelp)
        throw std::runtime_error(
            "echo|echojson \"message\" ...\n"
            "\nSimply echo back the input arguments. This command is for testing.\n"
            "\nThe difference between echo and echojson is that echojson has argument conversion enabled in the client-side table in"
            "freebank-cli and the GUI. There is no server-side difference."
        );

    return request.params;
}

static UniValue getinfo_deprecated(const JSONRPCRequest& request)
{
    throw JSONRPCError(RPC_METHOD_NOT_FOUND,
        "getinfo\n"
        "\nThis call was removed in version 0.16.0. Use the appropriate fields from:\n"
        "- getblockchaininfo: blocks, difficulty, chain\n"
        "- getnetworkinfo: version, protocolversion, timeoffset, connections, proxy, relayfee, warnings\n"
        "- getwalletinfo: balance, keypoololdest, keypoolsize, paytxfee, unlocked_until, walletversion\n"
        "\nfreebank-cli has the option -getinfo to collect and format these in the old format."
    );
}

//
// v0.2.16: BMM JSON-RPCs for an outside BMM engine (BitWindow's orchestrator):
// get_block_template, connect_block, get_bmm_inclusions. Contract:
// gateway/docs/distribution/FREEBANKD_BMM_RPC_SPEC.md as amended by freebank's
// reply of 2026-09-26 (inbox/distribution/2026-09-26-from-freebank-bmm-spec.md).
//
// Byte orders: critical_hash is h* = hashMerkleRoot as ConsensusHex (internal
// byte order, what the M8 carries). Every other hash is display order. All hex
// is lowercase.
//
// Money rule: connect_block answers false only on a definite rejection. Every
// passing failure is a JSON-RPC error, so the engine retries rather than
// retiring a paid-for block. RPC_BMM_RETRY (-40) marks the "ask again soon" refusals.
//

// One mutex for all four BMM RPCs, refreshbmm included: mapBMMBlocks, the
// template pin and the refusal time boxes below have no lock of their own.
// Lock order: this mutex, then the main block cache mutexes, then cs_main. It is
// never taken while one of those is held. BMMCache's own mutex is a leaf.
static std::timed_mutex csBMMRpc;

class BMMRpcLock
{
public:
    BMMRpcLock(const std::string& strMethod, int nSeconds)
    {
        if (!csBMMRpc.try_lock_for(std::chrono::seconds(nSeconds)))
            throw JSONRPCError(RPC_BMM_RETRY, strMethod + ": another BMM call is running; try again");
    }
    ~BMMRpcLock() { csBMMRpc.unlock(); }
};

// The template pinned for the current round (eCash tip T, side tip): every call
// in a round returns the same block, so a raise keeps the same h*. Guarded by csBMMRpc.
struct BMMTemplatePin
{
    uint256 hashMainTip;
    uint256 hashSideTip;
    CBlock block;
    CAmount nFees = 0;
    int nHeight = 0;
};
static std::unique_ptr<BMMTemplatePin> pBMMTemplatePin;

// h* -> T for recent templates, so get_bmm_inclusions can check T's child only.
// Guarded by csBMMRpc.
static std::map<uint256, uint256> mapBMMTemplateMainTip;
static std::deque<uint256> deqBMMTemplate;
static const size_t BMM_TEMPLATES_REMEMBERED = 64;

// Refusal time boxes: (key, first seen). Guarded by csBMMRpc.
static const int64_t BMM_REFUSAL_SECONDS = 60;
static std::pair<uint256, int64_t> bmmTimeBoxHeader;
static std::pair<uint256, int64_t> bmmTimeBoxPending;

// How many cached eCash blocks get_bmm_inclusions scans without a pinned T: the
// engine's 10-block connect horizon plus the tip.
static const size_t BMM_INCLUSION_WINDOW = 11;

// How far back connect_block looks for a block already on the active chain.
static const int BMM_RESEND_DEPTH = 11;

static bool BMMBidderIsEngine()
{
    return gArgs.GetArg("-bmmbidder", "") == "engine";
}

static void BMMRequireEnforcer(const std::string& strMethod)
{
    if (GetL1Transport() != L1Transport::ENFORCER)
        throw JSONRPCError(RPC_MISC_ERROR, strMethod + " needs -mainchaintransport=enforcer "
                           "(the legacy transport writes h* in the other byte order)");
}

static void BMMRefuseDuringImport(const std::string& strMethod)
{
    if (fImporting || fReindex)
        throw JSONRPCError(RPC_BMM_RETRY, strMethod + ": importing or reindexing blocks; try again when that finishes");
}

// How long a BMM RPC waits for another thread's eCash cache update (P2P, the
// ticker) before it answers -40: the engine's call deadline is 30 s.
static const int BMM_CACHE_WAIT_SECONDS = 5;

/** Refresh the node's eCash view as refreshbmm does; a failure is retryable. */
static void BMMRefreshMainView(const std::string& strMethod)
{
    bool fReorg = false;
    bool fBusy = false;
    std::vector<uint256> vDisconnected;
    if (!TryUpdateMainBlockHashCache(fReorg, vDisconnected, BMM_CACHE_WAIT_SECONDS, fBusy)) {
        if (fBusy)
            throw JSONRPCError(RPC_BMM_RETRY, strMethod + ": the eCash block cache is being updated by another thread; try again");
        throw JSONRPCError(RPC_BMM_RETRY, strMethod + ": failed to update the eCash block cache; try again");
    }

    if (fReorg)
        HandleMainchainReorg(vDisconnected);

    if (!CheckMainchainConnection())
        throw JSONRPCError(RPC_BMM_RETRY, strMethod + ": not connected to eCash; try again");
}

/** True while the refusal keyed by key is within its time box. */
static bool BMMWithinTimeBox(std::pair<uint256, int64_t>& box, const uint256& key)
{
    const int64_t nNow = GetTime();
    if (box.first != key) {
        box.first = key;
        box.second = nNow;
    }
    return nNow - box.second < BMM_REFUSAL_SECONDS;
}

static bool BMMGetPrevBlockCommit(const CBlock& block, uint256& hashPrevMain, uint256& hashPrevSide)
{
    if (block.vtx.empty() || !block.vtx[0]->IsCoinBase())
        return false;

    for (const CTxOut& out : block.vtx[0]->vout) {
        if (out.scriptPubKey.IsPrevBlockCommit(hashPrevMain, hashPrevSide))
            return true;
    }
    return false;
}

/** A block with merkle root h* among the last BMM_RESEND_DEPTH blocks of the active chain. */
static bool BMMOnActiveChain(const uint256& hashCritical)
{
    AssertLockHeld(cs_main);
    const CBlockIndex* pindex = chainActive.Tip();
    for (int i = 0; pindex && i < BMM_RESEND_DEPTH; i++, pindex = pindex->pprev) {
        if (pindex->hashMerkleRoot == hashCritical)
            return true;
    }
    return false;
}

/** A block with merkle root h* that this node marked failed. */
static bool BMMHaveFailedBlock(const uint256& hashCritical)
{
    AssertLockHeld(cs_main);
    for (const auto& entry : mapBlockIndex) {
        const CBlockIndex* pindex = entry.second;
        if (pindex->hashMerkleRoot == hashCritical && (pindex->nStatus & BLOCK_FAILED_MASK))
            return true;
    }
    return false;
}

static UniValue BMMTemplateToJSON(const BMMTemplatePin& pin)
{
    CDataStream ss(SER_NETWORK, PROTOCOL_VERSION); // with witness data, always
    ss << pin.block;

    UniValue block(UniValue::VOBJ);
    block.pushKV("prev_main_hash", pin.hashMainTip.GetHex());
    block.pushKV("prev_side_hash", pin.block.hashPrevBlock.GetHex());
    block.pushKV("merkle_root", pin.block.hashMerkleRoot.GetHex());
    block.pushKV("height", pin.nHeight);
    block.pushKV("hex", HexStr(ss.begin(), ss.end()));

    UniValue result(UniValue::VOBJ);
    result.pushKV("critical_hash", ConsensusHexFromUint256(pin.block.hashMerkleRoot));
    result.pushKV("block", block);
    result.pushKV("fees_sats", (int64_t)pin.nFees);
    return result;
}

UniValue get_block_template(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 0)
        throw std::runtime_error(
            "get_block_template\n"
            "\nA BMM block template for an outside BMM engine (BitWindow). The block builds on the side tip\n"
            "and commits to the current eCash tip T. Every call for the same (T, side tip) returns the same\n"
            "block; mempool and coinbase-tag changes apply from the next round. Needs the enforcer transport.\n"
            "Retryable refusals use code -40.\n"
            "\nResult:\n"
            "{\n"
            "  \"critical_hash\": \"hex\",   (string) h* = hashMerkleRoot, internal byte order (as the M8 carries it)\n"
            "  \"block\": {\n"
            "    \"prev_main_hash\": \"hex\", (string) T, display order\n"
            "    \"prev_side_hash\": \"hex\", (string) hashPrevBlock, display order\n"
            "    \"merkle_root\": \"hex\",    (string) hashMerkleRoot, display order\n"
            "    \"height\": n,             (numeric) side-chain height of the block\n"
            "    \"hex\": \"hex\"             (string) the serialized block, witness included; nTime and\n"
            "                                        hashMainchainBlock are set by connect_block\n"
            "  },\n"
            "  \"fees_sats\": n              (numeric) coinbase fees, in sats\n"
            "}\n"
            "\nExamples:\n"
            + HelpExampleCli("get_block_template", "")
            + HelpExampleRpc("get_block_template", "")
        );

    const std::string strMethod = "get_block_template";
    BMMRequireEnforcer(strMethod);
    BMMRpcLock lock(strMethod, 5);
    BMMRefuseDuringImport(strMethod);

    if (vpwallets.empty())
        throw JSONRPCError(RPC_WALLET_NOT_FOUND, "No wallet: the block's coinbase pays this node's wallet");

    BMMRefreshMainView(strMethod);

    // One snapshot of T; block creation gets it explicitly.
    const uint256 hashMainTip = bmmCache.GetLastMainBlockHash();
    if (hashMainTip.IsNull())
        throw JSONRPCError(RPC_BMM_RETRY, "The eCash block cache is empty; try again");

    uint256 hashSideTip;
    uint256 hashBetterHeader;
    {
        LOCK(cs_main);
        const CBlockIndex* pindexTip = chainActive.Tip();
        hashSideTip = pindexTip->GetBlockHash();
        if (pindexBestHeader && pindexBestHeader != pindexTip
                && pindexBestHeader->nHeight > pindexTip->nHeight
                && !(pindexBestHeader->nStatus & BLOCK_FAILED_MASK))
            hashBetterHeader = pindexBestHeader->GetBlockHash();
    }

    // A better side chain is known but not connected yet: a template on the old
    // tip would lose. Time-boxed, so a header that never connects cannot stop us.
    if (!hashBetterHeader.IsNull() && BMMWithinTimeBox(bmmTimeBoxHeader, hashBetterHeader))
        throw JSONRPCError(RPC_BMM_RETRY, "A better side-chain header is known but not connected yet; try again");

    // Same round: same block.
    if (pBMMTemplatePin && pBMMTemplatePin->hashMainTip == hashMainTip && pBMMTemplatePin->hashSideTip == hashSideTip)
        return BMMTemplateToJSON(*pBMMTemplatePin);

    // One bidder per node (opt-in): refreshbmm already bid on T.
    if (BMMBidderIsEngine() && bmmCache.HaveBMMRequestForPrevBlock(hashMainTip))
        throw JSONRPCError(RPC_BMM_RETRY, "refreshbmm already bid on this eCash tip (-bmmbidder=engine); try again on the next eCash block");

    // Pending: T itself carries a slot-130 commitment whose side block is not
    // connected yet. A template on the old side tip would lose to it on first
    // seen. Time-boxed (a junk h* must not stop bidding) and never when that
    // block is marked failed.
    uint256 hashCommitT;
    const L1Client::Commitment commitT = GetL1Client().ReadBmmCommitment(hashMainTip, hashCommitT);
    if (commitT == L1Client::Commitment::UNKNOWN)
        throw JSONRPCError(RPC_BMM_RETRY, "Could not read the eCash tip's BMM commitment; try again");
    if (commitT == L1Client::Commitment::COMMITTED) {
        bool fSettled = false;
        {
            LOCK(cs_main);
            fSettled = chainActive.Tip()->hashMainBlock == hashMainTip
                || BMMOnActiveChain(hashCommitT)
                || BMMHaveFailedBlock(hashCommitT);
        }
        if (!fSettled && BMMWithinTimeBox(bmmTimeBoxPending, hashMainTip))
            throw JSONRPCError(RPC_BMM_RETRY, "The side block for this eCash tip is pending; try again");
    }

    CBlock block;
    CAmount nFees = 0;
    std::string strError;
    if (!BlockAssembler(Params(), BMMTemplateAssemblerOptions()).GenerateBMMBlock(block, strError, &nFees, std::vector<CMutableTransaction>(),
                uint256(), CScript(), hashMainTip))
        throw JSONRPCError(RPC_BMM_RETRY, "Failed to build a BMM block: " + strError);

    if (block.hashPrevBlock != hashSideTip)
        throw JSONRPCError(RPC_BMM_RETRY, "The side tip moved while the template was built; try again");

    uint256 hashPrevMain;
    uint256 hashPrevSide;
    if (!BMMGetPrevBlockCommit(block, hashPrevMain, hashPrevSide) || hashPrevMain != hashMainTip || hashPrevSide != hashSideTip)
        throw JSONRPCError(RPC_INTERNAL_ERROR, "The built block's PrevBlockCommit does not match its eCash tip");

    int nHeight = 0;
    {
        LOCK(cs_main);
        BlockMap::iterator mi = mapBlockIndex.find(hashSideTip);
        if (mi == mapBlockIndex.end())
            throw JSONRPCError(RPC_BMM_RETRY, "The side tip vanished; try again");
        nHeight = mi->second->nHeight + 1;
    }

    pBMMTemplatePin.reset(new BMMTemplatePin());
    pBMMTemplatePin->hashMainTip = hashMainTip;
    pBMMTemplatePin->hashSideTip = hashSideTip;
    pBMMTemplatePin->block = block;
    pBMMTemplatePin->nFees = nFees;
    pBMMTemplatePin->nHeight = nHeight;

    if (!mapBMMTemplateMainTip.count(block.hashMerkleRoot)) {
        mapBMMTemplateMainTip[block.hashMerkleRoot] = hashMainTip;
        deqBMMTemplate.push_back(block.hashMerkleRoot);
        while (deqBMMTemplate.size() > BMM_TEMPLATES_REMEMBERED) {
            mapBMMTemplateMainTip.erase(deqBMMTemplate.front());
            deqBMMTemplate.pop_front();
        }
    }

    LogPrintf("%s: template h* %s at side height %d on eCash tip %s\n", __func__,
              ConsensusHexFromUint256(block.hashMerkleRoot), nHeight, hashMainTip.ToString());

    return BMMTemplateToJSON(*pBMMTemplatePin);
}

namespace {
class BMMStateCatcher : public CValidationInterface
{
public:
    uint256 hash;
    bool found;
    CValidationState state;

    explicit BMMStateCatcher(const uint256& hashIn) : hash(hashIn), found(false), state() {}

protected:
    void BlockChecked(const CBlock& block, const CValidationState& stateIn) override {
        if (block.GetHash() != hash)
            return;
        found = true;
        state = stateIn;
    }
};
}

// Reject reasons that can come from a passing condition (an L1 answer, a cache
// race, the clock, a missing parent), not from the block. A block rejected for
// one of these is not definitely rejected.
static bool BMMIsPassingRejectReason(const std::string& strReason)
{
    return strReason == "prev-blk-not-found"
        || strReason == "time-too-new"
        || strReason == "bad-mc-prev"               // the eCash cache is checked before; a mismatch now is a race
        || strReason == "duplicate"                 // marked failed by another thread after the clear above
        || strReason == "bad-prevblk"               // the parent was marked during this call (see connect_block)
        || strReason == "bad-bmm"                   // VerifyBMM cannot tell "L1 down" from "not committed"
        || strReason == "invalid-sidechain-deposit"; // VerifyDeposit likewise, until N13
}

UniValue connect_block(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 2)
        throw std::runtime_error(
            "connect_block {block} \"main_block_hash\"\n"
            "\nConnect a block from get_block_template whose h* was committed in eCash block main_block_hash.\n"
            "Sets nTime (the eCash block's time) and hashMainchainBlock, then processes the block.\n"
            "Needs the enforcer transport.\n"
            "\nArguments:\n"
            "1. block              (object, required) the \"block\" object get_block_template returned (its \"hex\" is used)\n"
            "2. \"main_block_hash\"  (string, required) the eCash block that commits the block's h*, display order\n"
            "\nResult:\n"
            "true|false  (boolean) true: the block is on the active chain (also for a re-send).\n"
            "            false: the block is definitely rejected. Anything that may pass is a JSON-RPC error.\n"
            "\nExamples:\n"
            + HelpExampleCli("connect_block", "'{\"hex\":\"...\"}' \"0000...\"")
        );

    const std::string strMethod = "connect_block";

    // Parse the block from the JSON alone; malformed input is an error.
    const UniValue& obj = request.params[0];
    if (!obj.isObject())
        throw JSONRPCError(RPC_INVALID_PARAMETER, "block must be the object get_block_template returned");
    const UniValue& hex = find_value(obj, "hex");
    if (!hex.isStr() || !IsHex(hex.get_str()))
        throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "block.hex is missing or not hex");

    CBlock block;
    {
        std::vector<unsigned char> vch(ParseHex(hex.get_str()));
        CDataStream ss(vch, SER_NETWORK, PROTOCOL_VERSION);
        try {
            ss >> block;
        } catch (const std::exception&) {
            throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "block.hex does not decode as a block");
        }
        if (!ss.empty())
            throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "block.hex has trailing bytes");
    }
    if (block.vtx.empty() || !block.vtx[0]->IsCoinBase())
        throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "block has no coinbase");
    bool fMutated = false;
    if (BlockMerkleRoot(block, &fMutated) != block.hashMerkleRoot || fMutated)
        throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "block's merkle root does not match its transactions");

    uint256 hashPrevMain;
    uint256 hashPrevSide;
    if (!BMMGetPrevBlockCommit(block, hashPrevMain, hashPrevSide))
        throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "block's coinbase has no PrevBlockCommit");

    const uint256 hashMain = ParseHashV(request.params[1], "main_block_hash");
    const uint256 hashCritical = block.hashMerkleRoot;

    BMMRequireEnforcer(strMethod);
    BMMRpcLock lock(strMethod, 30);

    // A re-send of a block already on the active chain: answered from the
    // chain alone (merkle root only), so it holds while the L1 is down.
    {
        LOCK(cs_main);
        if (BMMOnActiveChain(hashCritical))
            return true;
    }

    BMMRefuseDuringImport(strMethod);
    BMMRefreshMainView(strMethod);

    // The eCash block to connect through: M when it is T's child on this
    // node's eCash chain; otherwise (M orphaned in a 1-block race, or not seen
    // yet) T's child M' on this node's chain, if M' commits the same h*.
    const uint256 hashUse = bmmCache.GetMainBlockThroughT(hashMain, hashPrevMain);
    if (hashUse.IsNull())
        throw JSONRPCError(RPC_BMM_RETRY, strprintf("eCash block %s is not on this node's eCash chain as the child of %s yet; try again",
                    hashMain.ToString(), hashPrevMain.ToString()));

    uint256 hashCommit;
    const L1Client::Commitment commit = GetL1Client().ReadBmmCommitment(hashUse, hashCommit);
    if (commit == L1Client::Commitment::UNKNOWN || commit == L1Client::Commitment::NOT_FOUND)
        throw JSONRPCError(RPC_BMM_RETRY, strprintf("Could not read eCash block %s's BMM commitment; try again", hashUse.ToString()));
    if (commit != L1Client::Commitment::COMMITTED || hashCommit != hashCritical)
        throw JSONRPCError(RPC_BMM_RETRY, strprintf("eCash block %s does not commit this block's h*", hashUse.ToString()));

    // nTime comes from the eCash block, never from the caller.
    uint256 txid;
    uint32_t nTime = 0;
    SidechainClient client;
    if (!client.VerifyBMM(hashUse, hashCritical, txid, nTime) || nTime == 0)
        throw JSONRPCError(RPC_BMM_RETRY, strprintf("Could not verify BMM in eCash block %s; try again", hashUse.ToString()));

    block.nTime = nTime;
    block.hashMainchainBlock = hashUse;
    const uint256 hashBlock = block.GetHash();

    {
        LOCK(cs_main);
        BlockMap::iterator mi = mapBlockIndex.find(block.hashPrevBlock);
        if (mi != mapBlockIndex.end())
            UpdateUncommittedBlockStructures(block, mi->second, Params().GetConsensus());

        // The side block this one builds on is marked failed. get_block_template
        // built on it while it was the active tip, so the mark came later: from
        // HandleMainchainReorg (its eCash block was orphaned) or an operator's
        // invalidateblock. Neither is a verdict on this block, and a re-send of
        // the parent's own block clears it; so retry, never false, and never
        // clear the parent's mark from here.
        if (mi != mapBlockIndex.end() && (mi->second->nStatus & BLOCK_FAILED_MASK))
            throw JSONRPCError(RPC_BMM_RETRY, strprintf("The side block %s this block builds on is marked failed; try again",
                        block.hashPrevBlock.ToString()));

        // A mark already on this block is not a verdict from this call: it may
        // come from HandleMainchainReorg (its eCash block was orphaned, and has
        // just been found on this node's eCash chain again above) or from a
        // passing failure on another thread. Clear it, as reconsiderblock
        // would, so ProcessNewBlock gives a fresh verdict; a block that really
        // is invalid fails again with its reason.
        BlockMap::iterator miBlock = mapBlockIndex.find(hashBlock);
        if (miBlock != mapBlockIndex.end() && (miBlock->second->nStatus & BLOCK_FAILED_MASK)) {
            LogPrintf("%s: block %s was marked failed before this call; clearing the mark to check it again\n",
                      __func__, hashBlock.ToString());
            ResetBlockFailureFlags(miBlock->second);
        }
    }

    // No cs_main and no cache mutex held here: ProcessNewBlock takes them.
    std::shared_ptr<const CBlock> pblock = std::make_shared<const CBlock>(block);
    BMMStateCatcher sc(hashBlock);
    RegisterValidationInterface(&sc);
    bool fNewBlock = false;
    const bool fAccepted = ProcessNewBlock(Params(), pblock, /* fForceProcessing */ true, &fNewBlock);
    UnregisterValidationInterface(&sc);

    const std::string strReason = sc.found ? sc.state.GetRejectReason() : "";
    const bool fInvalid = sc.found && sc.state.IsInvalid() && !sc.state.CorruptionPossible();

    bool fResult = false;
    {
        LOCK(cs_main);
        BlockMap::iterator mi = mapBlockIndex.find(hashBlock);
        CBlockIndex* pindex = mi == mapBlockIndex.end() ? nullptr : mi->second;

        if ((pindex && chainActive.Contains(pindex)) || BMMOnActiveChain(hashCritical)) {
            fResult = true;
        } else if (fInvalid && BMMIsPassingRejectReason(strReason)) {
            // Not definite. If the node marked the block failed for it, clear
            // the mark (as reconsiderblock would) so a retry checks it again.
            if (pindex && (pindex->nStatus & BLOCK_FAILED_MASK))
                ResetBlockFailureFlags(pindex);
            throw JSONRPCError(RPC_BMM_RETRY, strprintf("Block not connected yet (%s); try again", strReason));
        } else if (fInvalid) {
            LogPrintf("%s: block %s (h* %s) definitely rejected: %s\n", __func__, hashBlock.ToString(),
                      ConsensusHexFromUint256(hashCritical), FormatStateMessage(sc.state));
            return false;
        } else if (pindex && pindex->pprev && (pindex->pprev->nStatus & BLOCK_FAILED_MASK)) {
            // Its parent was marked failed during this call (see above).
            throw JSONRPCError(RPC_BMM_RETRY, "The side block this block builds on was marked failed; try again");
        } else if (pindex && (pindex->nStatus & BLOCK_FAILED_MASK)) {
            // Marked with no verdict caught in this call: another thread did
            // it. Clear it and let the engine ask again.
            ResetBlockFailureFlags(pindex);
            throw JSONRPCError(RPC_BMM_RETRY, "Block marked failed outside this call; try again");
        } else if (fAccepted && pindex && (pindex->nStatus & BLOCK_HAVE_DATA) && chainActive.Height() >= pindex->nHeight) {
            // Stored and valid, but another block took its height first.
            LogPrintf("%s: block %s lost height %d to %s\n", __func__, hashBlock.ToString(), pindex->nHeight,
                      chainActive[pindex->nHeight]->GetBlockHash().ToString());
            return false;
        } else {
            throw JSONRPCError(RPC_BMM_RETRY, strprintf("Block not connected (%s); try again",
                        strReason.empty() ? (fAccepted ? "not on the active chain" : "processing failed") : strReason));
        }
    }

    if (fResult)
        SetNetworkActive(true, "connect_block RPC connected a block");

    return fResult;
}

UniValue get_bmm_inclusions(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "get_bmm_inclusions \"critical_hash\"\n"
            "\nThe eCash blocks on this node's eCash chain that commit h* for this sidechain, among the last 11\n"
            "cached eCash blocks (or only T's child, for a template this node built). An L1 failure is an error,\n"
            "never an empty list. Needs the enforcer transport.\n"
            "\nArguments:\n"
            "1. \"critical_hash\"  (string, required) h* as get_block_template returned it (internal byte order)\n"
            "\nResult:\n"
            "[ \"hash\", ... ]    (array) eCash block hashes, display order\n"
            "\nExamples:\n"
            + HelpExampleCli("get_bmm_inclusions", "\"0000...\"")
        );

    const std::string strMethod = "get_bmm_inclusions";

    const std::string strHex = request.params[0].get_str();
    const uint256 hashCritical = Uint256FromConsensusHex(strHex);
    if (hashCritical.IsNull())
        throw JSONRPCError(RPC_INVALID_PARAMETER, "critical_hash must be 64 hex characters");

    BMMRequireEnforcer(strMethod);
    BMMRpcLock lock(strMethod, 30);
    BMMRefuseDuringImport(strMethod);
    BMMRefreshMainView(strMethod);

    std::vector<uint256> vCandidate;
    {
        std::map<uint256, uint256>::const_iterator it = mapBMMTemplateMainTip.find(hashCritical);
        if (it != mapBMMTemplateMainTip.end()) {
            const uint256 hashChild = bmmCache.GetMainChildBlockHash(it->second);
            if (!hashChild.IsNull())
                vCandidate.push_back(hashChild);
        } else {
            vCandidate = bmmCache.GetLastMainBlockHashes(BMM_INCLUSION_WINDOW);
        }
    }

    UniValue result(UniValue::VARR);
    for (const uint256& hashMain : vCandidate) {
        uint256 hashCommit;
        const L1Client::Commitment commit = GetL1Client().ReadBmmCommitment(hashMain, hashCommit);
        if (commit == L1Client::Commitment::UNKNOWN)
            throw JSONRPCError(RPC_BMM_RETRY, strprintf("Could not read eCash block %s's BMM commitment; try again", hashMain.ToString()));
        if (commit == L1Client::Commitment::COMMITTED && hashCommit == hashCritical)
            result.push_back(hashMain.GetHex());
    }

    return result;
}

UniValue setcoinbasetag(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "setcoinbasetag \"name\"\n"
            "\nSet the name this node writes into the coinbase of the blocks it produces, as -coinbasetag does,\n"
            "until the next restart (freebank.conf stays the source). \"\" clears it. A pinned\n"
            "get_block_template round keeps its block; the new name applies from the next round.\n"
            "\nArguments:\n"
            "1. \"name\"  (string, required) 1 to 64 printable ASCII characters, or \"\" for no tag\n"
            "\nResult:\n"
            "\"name\"    (string) the tag now in use\n"
            "\nExamples:\n"
            + HelpExampleCli("setcoinbasetag", "\"my pool\"")
        );

    const std::string strIn = request.params[0].get_str();
    std::string strTag;
    CScript scriptTag;
    if (strIn.find_first_not_of(" \t\r\n") != std::string::npos) {
        std::string strError;
        if (!ParseCoinbaseTag(strIn, strTag, scriptTag, strError))
            throw JSONRPCError(RPC_INVALID_PARAMETER, strError);
    }

    {
        // IncrementExtraNonce, the only reader, runs under cs_main.
        LOCK(cs_main);
        COINBASE_FLAGS = scriptTag;
    }
    LogPrintf("Coinbase tag set by RPC: \"%s\"\n", strTag);

    return strTag;
}

UniValue refreshbmm(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() < 1 || request.params.size() > 3)
        throw std::runtime_error(
            "refreshbmm\n"
            "\nRefresh automated BMM. Basic testing implementation\n"
            "\nArguments:\n"
            "1. \"amount\"                (numeric) Amount to pay mainchain miner for including BMM request (required)\n"
            "2. \"createnew\" true|false  (bool) Create a new BMM block if possible\n (optional, default: true)\n"
            "3. \"prevblock\"             (string) Hash of sidechain block to build on (optional, default: chaintip)\n"
            "\nResult:\n"
            "hash_last_main_block  (string) Hash of mainchain tip.\n"
            "bmm_block_created     (string) Hash of new BMM block created.\n"
            "bmm_block_submitted   (string) Hash of BMM block connected to sidechain.\n"
            "ntxn                  (number) Number of txn in new BMM request (if created).\n"
            "nfees                 (number) Total fees in new block (if created).\n"
            "txid                  (string) Mainchain BMM request TXID.\n"
            "error                 (string) Output from sidechain client.\n"
        );

    // v0.2.16: not while stored blocks are being imported or replayed
    // (-reindex, -loadblock, startup). The replay's tip is not this node's
    // chain yet, so a block built or connected now would build on the wrong
    // one, and mainchain reorgs are held until the import is done.
    // v0.2.16: one mutex for all four BMM RPCs (mapBMMBlocks has no lock)
    BMMRpcLock lock("refreshbmm", 30);

    if (fImporting || fReindex)
        throw JSONRPCError(RPC_CLIENT_IN_INITIAL_DOWNLOAD, "Importing or reindexing blocks; refreshbmm is refused until that finishes");

    bool fReorg = false;
    std::vector<uint256> vDisconnected;
    if (!UpdateMainBlockHashCache(fReorg, vDisconnected))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to update mainchain block cache!");

    if (fReorg)
        HandleMainchainReorg(vDisconnected);

    CAmount amount = AmountFromValue(request.params[0]);
    if (amount <= 0)
        throw JSONRPCError(RPC_TYPE_ERROR, "Invalid amount for BMM!");

    // Whether or not to create a new BMM block / request if possible. If set
    // false, we will only check for BMM commits in the mainchain and try to
    // connect those blocks but not generate a new BMM block and request.
    bool fCreateNew = request.params.size() >= 2 ? request.params[1].get_bool() : true;

    // v0.2.16 one-bidder guard (opt-in): when an outside engine bids through
    // get_block_template, refreshbmm still scans for and connects won blocks
    // but never places a bid of its own.
    if (fCreateNew && BMMBidderIsEngine())
        fCreateNew = false;

    // If hashPrevBlock is set, we will build a block on top of that block
    // instead of the current sidechain tip.
    uint256 hashPrevBlock;
    if (request.params.size() == 3) {
        LOCK(cs_main);

        hashPrevBlock = uint256S(request.params[2].get_str());
        if (hashPrevBlock.IsNull())
            throw JSONRPCError(RPC_MISC_ERROR, "Invalid prev block hash (null)!");

        // Check if the prevblock is in the side: chain
        if (mapBlockIndex.count(hashPrevBlock) == 0)
            throw JSONRPCError(RPC_MISC_ERROR, "Prev block does not exist!");
    }

    if (!CheckMainchainConnection())
        throw JSONRPCError(RPC_MISC_ERROR, "Must be connected to mainchain (not connected)!");

    SetNetworkActive(true, "refreshbmm RPC command issued");

    SidechainClient client;
    std::string strError = "";
    uint256 hashCreated;
    uint256 hashConnected;
    uint256 hashConnectedBlind;
    uint256 txid;
    int ntxn = 0;
    CAmount nFees = 0;
    if (!client.RefreshBMM(amount, strError, hashCreated, hashConnected, hashConnectedBlind, txid, ntxn, nFees, fCreateNew, hashPrevBlock))
        throw JSONRPCError(RPC_MISC_ERROR, strError);

    UniValue result(UniValue::VOBJ);
    result.pushKV("hash_last_main_block", bmmCache.GetLastMainBlockHash().ToString());
    result.pushKV("bmm_block_created", hashCreated.ToString());
    result.pushKV("bmm_block_submitted", hashConnected.ToString());
    result.pushKV("bmm_block_submitted_blind", hashConnectedBlind.ToString());
    result.pushKV("ntxn", ntxn);
    result.pushKV("nfees", nFees);
    result.pushKV("txid", txid.ToString());
    result.pushKV("error", strError);

    return result;
}

UniValue getaveragemainchainfees(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 2)
        throw std::runtime_error(
            "getaveragemainchainfees\n"
            "\nArguments:\n"
            "1. \"numblocks (numeric, required) the number of blocks to scan\"\n"
            "2. \"startheight (numeric, required) the block height to start scanning at\"\n"
            "\nGet the average transaction fees from the mainchain\n"
            "\nResult:\n"
            "averagefees  (numeric) x.xx\n"
        );

    int nBlocks = request.params[0].get_int();
    int nStartHeight = request.params[1].get_int();

    SidechainClient client;
    CAmount nAverageFees = 0;
    if (!client.GetAverageFees(nBlocks, nStartHeight, nAverageFees))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to request fee average!");

    UniValue result(UniValue::VOBJ);
    result.pushKV("fees", ValueFromAmount(nAverageFees));

    return result;
}

UniValue getmainchainblockcount(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size())
        throw std::runtime_error(
            "getmainchainblockcount\n"
            "\nArguments: none\n"
            "\nGet the mainchain block count\n"
            "\nResult:\n"
            "blockcount  (numeric) x\n"
        );

    SidechainClient client;
    int nBlocks = 0;
    if (!client.GetBlockCount(nBlocks))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to request mainchain height!");

    UniValue result(UniValue::VOBJ);
    result.pushKV("blockcount", nBlocks);

    return result;
}

UniValue getmainchainblockhash(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "getmainchainblockhash\n"
            "\nArguments:\n"
            "1. \"height (numeric, required) the mainchain block height\"\n"
            "\nGet the mainchain block hash\n"
            "\nResult:\n"
            "hashblock  (string)\n"
        );

    int nHeight = request.params[0].get_int();

    SidechainClient client;
    uint256 hashBlock;
    if (!client.GetBlockHash(nHeight, hashBlock))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to request mainchain block hash!");

    UniValue result(UniValue::VOBJ);
    result.pushKV("blockhash", hashBlock.ToString());

    return result;
}

UniValue verifymainblockcache(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size())
        throw std::runtime_error(
            "verifymainblockcache\n"
            "\nArguments: None\n"
            "\nVerify our cache of mainchain block hashes with the mainchain.\n"
            "\nResult:\n"
            "height        (numeric) Cache verified to this mainchain block height.\n"
            "checked_from  (numeric) Lowest height compared; heights below it follow by prevblock links.\n"
        );

    // v0.2.16: checks the newest MAIN_BLOCK_CACHE_VERIFY_TAIL heights in one
    // batch; the cache is built along prevblock links, so a match at the
    // oldest of them covers everything below.
    std::string strError = "";
    MainBlockCacheCheck check;
    if (!VerifyMainBlockCache(strError, &check))
        throw JSONRPCError(RPC_MISC_ERROR, strError);

    UniValue result(UniValue::VOBJ);
    result.pushKV("height", check.nTo);
    result.pushKV("checked_from", check.nFrom);

    return result;
}

UniValue updatemainblockcache(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size())
        throw std::runtime_error(
            "updatemainblockcache\n"
            "\nArguments: None\n"
            "\nSync our cache of mainchain block hashes with the mainchain.\n"
            "\nResult:\n"
            "reorg          (true/false)\n"
            "disconnected   (numeric)\n"
            "cached         (numeric)\n"
            "cachesize      (numeric)\n"
        );


    int nCached = bmmCache.GetCachedBlockCount();

    bool fReorg = false;
    std::vector<uint256> vDisconnected;
    if (!UpdateMainBlockHashCache(fReorg, vDisconnected))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to update!");

    if (fReorg)
        HandleMainchainReorg(vDisconnected);

    int nCachedResult = bmmCache.GetCachedBlockCount();

    UniValue result(UniValue::VOBJ);
    result.pushKV("reorg", fReorg);
    result.pushKV("disconnected", (uint64_t)vDisconnected.size());
    result.pushKV("cached", nCachedResult - nCached);
    result.pushKV("cachesize", nCachedResult);

    return result;
}

UniValue listmywithdrawals(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size())
        throw std::runtime_error(
            "listmywithdrawals\n"
            "\nArguments: None\n"
            "\nList your sidechain withdrawals.\n"
            "\nResult:\n"
            "id             (string)\n"
        );

    std::set<uint256> setID = bmmCache.GetCachedWithdrawalID();

    UniValue result(UniValue::VARR);
    for (const uint256& u : setID) {
        UniValue obj(UniValue::VOBJ);
        obj.pushKV("id", u.ToString());
        result.push_back(obj);
    }

    return result;
}

UniValue rebroadcastwithdrawalbundle(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size())
        throw std::runtime_error(
            "rebroadcastwithdrawalbundle\n"
            "\nHand the latest WithdrawalBundle to the mainchain again. The node already does this by itself,\n"
            "on each block it connects, until one attempt succeeds.\n"
            "With -mainchaintransport=enforcer the bundle goes to the enforcer's block producer\n"
            "(BlockProducerService/ProposeWithdrawalBundle, or WalletService/BroadcastWithdrawalBundle on\n"
            "an enforcer older than 7958cef). The enforcer stores it and proposes it (M3) in the mainchain\n"
            "blocks it produces; nothing is broadcast to the mainchain network.\n"
            "With -mainchaintransport=jsonrpc it is sent to the local mainchain node (receivewithdrawalbundle).\n"
        );

    SidechainWithdrawalBundle withdrawalBundle;
    uint256 hashLatest;
    psidechaintree->GetLastWithdrawalBundleHash(hashLatest);

    if (hashLatest.IsNull())
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to lookup latest WithdrawalBundle hash!");

    if (!psidechaintree->GetWithdrawalBundle(hashLatest, withdrawalBundle))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to load latest WithdrawalBundle from database");

    SidechainClient client;
    std::string strHex = EncodeHexTx(withdrawalBundle.tx);
    if (!client.BroadcastWithdrawalBundle(strHex))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to broadcast latest WithdrawalBundle");

    return NullUniValue;
}

UniValue getwithdrawalbundle(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size())
        throw std::runtime_error(
            "getwithdrawalbundle\n"
            "\nGet the latest WithdrawalBundle transaction hex.\n"
        );

    SidechainWithdrawalBundle withdrawalBundle;
    uint256 hashLatest;
    psidechaintree->GetLastWithdrawalBundleHash(hashLatest);

    if (hashLatest.IsNull())
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to lookup latest WithdrawalBundle hash!");

    if (!psidechaintree->GetWithdrawalBundle(hashLatest, withdrawalBundle))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to load latest WithdrawalBundle from database");

    return EncodeHexTx(withdrawalBundle.tx);
}

UniValue getwithdrawal(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "getwithdrawal \"id\"\n"
            "\nGet withdrawal information\n"
            "\nArguments:\n"
            "1. \"id\"   (string, required) the withdrawal ID\n"
            "\nResult:\n"
            "{\n"
            "  \"destination\" : \"str\",      (string) the mainchain address paid, in its mainchain form\n"
            "  \"destination_raw\" : \"str\",  (string) the stored destination string (bech32/P2SH destinations are\n"
            "                                stored in a sidechain-looking carrier form; never send FreeBank coins to it)\n"
            "  \"scriptpubkey\" : \"hex\",     (string) the mainchain payout script (empty if the stored string does not decode)\n"
            "  \"refunddestination\" : \"str\",(string)\n"
            "  \"amount\" : n,                (numeric) sats, payout + mainchain fee\n"
            "  \"amountmainchainfee\" : n,    (numeric) sats\n"
            "  \"status\" : \"str\",           (string)\n"
            "  \"hashblindtx\" : \"hex\"       (string)\n"
            "}\n"
        );

    uint256 id = uint256S(request.params[0].get_str());
    if (id.IsNull())
        throw JSONRPCError(RPC_MISC_ERROR, "Invalid ID!");

    SidechainWithdrawal wt;
    if (!psidechaintree->GetWithdrawal(id, wt))
        throw JSONRPCError(RPC_MISC_ERROR, "Withdrawal does not exist!");

    UniValue result(UniValue::VOBJ);
    const CScript scriptPayout = MainchainPayoutScript(wt.strDestination);
    result.pushKV("destination", MainchainDisplayAddress(wt.strDestination));
    result.pushKV("destination_raw", wt.strDestination);
    result.pushKV("scriptpubkey", HexStr(scriptPayout.begin(), scriptPayout.end()));
    result.pushKV("refunddestination", wt.strRefundDestination);
    result.pushKV("amount", wt.amount);
    result.pushKV("amountmainchainfee",wt.mainchainFee );
    result.pushKV("status", wt.GetStatusStr());
    result.pushKV("hashblindtx", wt.hashBlindTx.ToString());

    return result;
}

UniValue formatdepositaddress(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "formatdepositaddress \"address\"\n"
            "\nTakes any string and returns a sidechain deposit address\n"
            "Use this command to turn a sidechain receiving address into a deposit address.\n"
            "\nArguments:\n"
            "1. \"address\"      (string, required) The destination to be formatted as a deposit address\n"
            "\nResult:\n"
            "deposit address\n"
            "\nExamples:\n"
            + HelpExampleCli("formatdepositaddress", "\"1PSSGeFHDnKNxiEyFrD1wcEaHr9hrQDDWc\"")
            + HelpExampleRpc("formatdepositaddress", "\"1PSSGeFHDnKNxiEyFrD1wcEaHr9hrQDDWc\"")
        );

    std::string strAddress = request.params[0].get_str();
    if (strAddress.empty())
        throw JSONRPCError(RPC_MISC_ERROR, "Input is blank!");


    std::string strDepositAddress = GenerateDepositAddress(strAddress);
    std::string strAddressOut = "";
    unsigned int nSidechainOut;
    if (!ParseDepositAddress(strDepositAddress, strAddressOut, nSidechainOut))
        throw JSONRPCError(RPC_MISC_ERROR, "Failed to verify deposit address!");

    return strDepositAddress;
}

UniValue listassets(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size())
        throw std::runtime_error(
            "listassets\n"
            "\nList BitAssets\n"
            "\nResult:\n"
            "Array of BitAssets\n"
            "\nExamples:\n"
            + HelpExampleCli("listassets", "")
            + HelpExampleRpc("listassets", "")
        );

    std::vector<BitAsset> vAsset = passettree->GetAssets();

    UniValue result(UniValue::VARR);
    for (const BitAsset& b : vAsset) {
        UniValue obj(UniValue::VOBJ);
        obj.pushKV("id", (uint64_t)b.nID);
        obj.pushKV("ticker", b.strTicker);
        obj.pushKV("supply", b.nSupply);
        obj.pushKV("headline", b.strHeadline);
        obj.pushKV("payload", b.payload.ToString());
        obj.pushKV("txid", b.txid.ToString());
        obj.pushKV("controller", b.strController);
        obj.pushKV("owner", b.strOwner);
        result.push_back(obj);
    }

    return result;
}

static UniValue BillToJSON(const CBill& bill, bool fIncludeBody)
{
    UniValue obj(UniValue::VOBJ);
    obj.pushKV("id", (uint64_t)bill.nBillID);
    obj.pushKV("bill_id", bill.billID.ToString());
    obj.pushKV("amount", ValueFromAmount(bill.amount));
    obj.pushKV("amount_grams", GramsUV((int64_t)bill.amount));
    obj.pushKV("escrow", ValueFromAmount(bill.amountEscrow));
    obj.pushKV("escrow_grams", GramsUV((int64_t)bill.amountEscrow));
    obj.pushKV("status", std::string(1, bill.status));
    obj.pushKV("issued_height", (uint64_t)bill.nIssuedHeight);
    obj.pushKV("maturity_height", (uint64_t)bill.nMaturityHeight);
    obj.pushKV("grace_blocks", (uint64_t)bill.nGraceBlocks);
    obj.pushKV("drawer_pubkey", HexStr(bill.vchDrawerPubKey));
    obj.pushKV("acceptor_pubkey", HexStr(bill.vchAcceptorPubKey));
    obj.pushKV("holder_pubkey", HexStr(bill.vchHolderPubKey));
    // B1: 0 unless a discount house holds this bill in its loan book. Exposed
    // because the deep-reorg gate byte-compares CBill across nodes, and this is
    // the field that discriminates the canonical-minimal encoding - without it
    // the comparison silently cannot see the one field ops 5-8 move.
    obj.pushKV("owner_house_id", (uint64_t)bill.nOwnerHouseID);
    obj.pushKV("issue_txid", bill.txidIssue.ToString());
    obj.pushKV("escrow_outpoint", bill.outEscrow.hash.ToString() + ":" + itostr(bill.outEscrow.n));
    obj.pushKV("title_outpoint", bill.outTitle.hash.ToString() + ":" + itostr(bill.outTitle.n));

    UniValue endorsements(UniValue::VARR);
    for (const BillEndorsement& e : bill.vEndorsement) {
        UniValue eo(UniValue::VOBJ);
        eo.pushKV("from", HexStr(e.vchFrom));
        eo.pushKV("to", HexStr(e.vchTo));
        eo.pushKV("at_height", (uint64_t)e.nAtHeight);
        endorsements.push_back(eo);
    }
    obj.pushKV("endorsements", endorsements);

    if (fIncludeBody)
        obj.pushKV("encrypted_body", HexStr(bill.vchEncryptedBody));

    return obj;
}

UniValue listbills(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 0)
        throw std::runtime_error(
            "listbills\n"
            "List all bills of exchange tracked by the node\n"
            "\nResult (array of bill objects)\n"
            "\nExamples:\n"
            + HelpExampleCli("listbills", "")
            + HelpExampleRpc("listbills", "")
        );

    LOCK(cs_main);

    UniValue ret(UniValue::VARR);
    for (const CBill& bill : pbilltree->GetBills())
        ret.push_back(BillToJSON(bill, false /* fIncludeBody */));

    return ret;
}

UniValue listloanbook(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() > 1)
        throw std::runtime_error(
            "listloanbook ( house_id )\n"
            "\nThe discounted bills a house holds - its loan book (Phase 3.9).\n"
            "With no argument, every house-held bill on the chain.\n"
            "\nArguments:\n"
            "1. house_id      (numeric, optional) restrict to one house\n"
            "\nResult:\n"
            "{\n"
            "  \"house_id\": n,             (numeric) 0 when unfiltered\n"
            "  \"count\": n,                (numeric) bills held\n"
            "  \"face_total\": n,           (numeric) summed face, sats\n"
            "  \"recorded_face\": n,        (numeric) the house's own nLoanBookFace\n"
            "  \"face_matches\": true|false,(boolean) the two agree - the state invariant\n"
            "  \"wtd_avg_maturity\": n,     (numeric) sum(face*maturity)/sum(face), as a height\n"
            "  \"bills\": [ ... ]           (array) the bill records\n"
            "}\n"
            "\nface_total is summed from the BILL records; recorded_face is the counter the\n"
            "house carries. They must be equal - that is the loan-book state invariant, and\n"
            "publishing both is what makes a divergence visible rather than latent.\n"
            "\nwtd_avg_maturity is the book's DURATION - the half of match funding a face\n"
            "total cannot show, and the quantity the rule is actually computed against.\n"
            "\nExamples:\n"
            + HelpExampleCli("listloanbook", "3")
            + HelpExampleRpc("listloanbook", "3")
        );

    const uint32_t nFilter = request.params.size() > 0 ? (uint32_t)request.params[0].get_int() : 0;

    LOCK(cs_main);

    UniValue bills(UniValue::VARR);
    uint64_t nCount = 0;
    CAmount amountFace = 0;
    for (const CBill& bill : pbilltree->GetBills()) {
        if (bill.nOwnerHouseID == 0)
            continue;
        if (nFilter != 0 && bill.nOwnerHouseID != nFilter)
            continue;
        bills.push_back(BillToJSON(bill, false /* fIncludeBody */));
        nCount++;
        amountFace += bill.amount;
    }

    UniValue ret(UniValue::VOBJ);
    ret.pushKV("house_id", (uint64_t)nFilter);
    ret.pushKV("count", nCount);
    ret.pushKV("face_total", amountFace);
    ret.pushKV("face_total_grams", GramsUV((int64_t)amountFace));
    if (nFilter != 0) {
        CHouse house;
        const bool fHave = phousetree->GetHouse(nFilter, house);
        ret.pushKV("recorded_face", fHave ? house.nLoanBookFace : 0);
        ret.pushKV("face_matches", fHave && house.nLoanBookFace == (uint64_t)amountFace);
        // The book's DURATION, which is the half of match funding a face total
        // cannot show: sum(face * maturity) / sum(face). Published as a height
        // so it reads against the tip directly. Derived from the house's own
        // 128-bit weight, so a divergence from the records shows up as
        // face_matches false rather than as a quietly wrong average.
        if (fHave && house.nLoanBookFace > 0) {
            const unsigned __int128 nAvg = house.LoanWtMaturity() / (unsigned __int128)house.nLoanBookFace;
            ret.pushKV("wtd_avg_maturity", (uint64_t)nAvg);
        } else {
            ret.pushKV("wtd_avg_maturity", (uint64_t)0);
        }
    }
    ret.pushKV("bills", bills);
    return ret;
}

UniValue getbill(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "getbill\n"
            "\nArguments:\n"
            "1. id            (numeric, required) the bill ID number\n"
            "\nGet one bill of exchange (full record incl. encrypted body)\n"
            "\nExamples:\n"
            + HelpExampleCli("getbill", "1")
            + HelpExampleRpc("getbill", "1")
        );

    const uint32_t nBillID = request.params[0].get_int();

    LOCK(cs_main);

    CBill bill;
    if (!pbilltree->GetBill(nBillID, bill))
        throw JSONRPCError(RPC_MISC_ERROR, "Unknown bill!");

    return BillToJSON(bill, true /* fIncludeBody */);
}


static UniValue HouseToJSON(const CHouse& house)
{
    UniValue obj(UniValue::VOBJ);
    obj.pushKV("id", (uint64_t)house.nHouseID);
    obj.pushKV("househash", house.houseID.ToString());
    obj.pushKV("tier", house.nTier);
    obj.pushKV("threshold", (uint64_t)house.nThresholdM);
    obj.pushKV("classid", house.strClassID);
    obj.pushKV("denominationmggold", house.nDenomMgGold);
    obj.pushKV("lambdax10", (uint64_t)HOUSE_LAMBDA_X10[house.nTier <= MAX_HOUSE_TIER ? house.nTier : 0]);
    obj.pushKV("activeescrow", ValueFromAmount(house.ActiveEscrow()));
    obj.pushKV("activeescrow_grams", GramsUV((int64_t)house.ActiveEscrow()));
    obj.pushKV("mintedunits", house.nMintedUnits);
    obj.pushKV("mintedunits_grams", GramsUV((int64_t)house.nMintedUnits));
    // Term-deposit accounting (Phase 3.8): the D in the shared cap N + D <=
    // lambda*E, and the weighted-average REMAINING term (blocks) of the deposit
    // book - the market's view of the maturity profile (a full bucketed ladder
    // lands with the wallet in T-i10). match_funding is the attestation-checked
    // long-vs-short rule (vacuously true in v1 - no loan book yet).
    obj.pushKV("depositunits", house.nDepositUnits);
    obj.pushKV("depositwam", (uint64_t)HouseDepositWAM(house, chainActive.Height() + 1));
    obj.pushKV("matchfundingok", HouseMatchFundingOK(house, chainActive.Height() + 1));
    // Raw weighted-maturity accumulator (Sigma principal*maturity), the two u64
    // words of the 128-bit value. Height-independent house state - the reorg gate
    // folds these into its canonical signature so a DisconnectBlock undo of a
    // deposit op is checked byte-exact, not just via the depositunits counter.
    obj.pushKV("depositwtmathi", house.nDepositWtMatHi);
    obj.pushKV("depositwtmatlo", house.nDepositWtMatLo);
    // B1 loan book: face value of the bills this house holds, and the same
    // 128-bit weighted-maturity accumulator on the ASSET side. These three are
    // exactly what a DISCOUNT / HRETIRE / HCLAIM moves, so the reorg gate folds
    // them into its canonical signature - without them a byte-compare across
    // nodes cannot see the loan-book half of the undo at all, and (because the
    // gate's field reader defaults a missing key to 0) would pass GREEN against
    // a completely broken one.
    obj.pushKV("loanbookface", house.nLoanBookFace);
    obj.pushKV("loanwtmathi", house.nLoanWtMatHi);
    obj.pushKV("loanwtmatlo", house.nLoanWtMatLo);
    // The CUSTODY key. Already load-bearing for redemption; B1 makes it the one
    // place a discounted bill's title may land (check 14) and the only address
    // an HRETIRE may pay (check 28). Publishing it is what lets an observer
    // verify either of those from the chain alone - without it "the title landed
    // on the house's consensus-known key" is unfalsifiable from outside.
    obj.pushKV("redemptiondestpk", HexStr(house.vchRedemptionDestPK));
    obj.pushKV("insolventdepositprincipal", house.nInsolventDepositPrincipal);
    // The BINDING cap is the min of the two (3.5 D2): capital (lambda*escrow)
    // and reserve (attested till / rho). Publish all three - the market prices
    // which constraint is binding.
    obj.pushKV("mintcapunits", HouseMintCapUnits(house));
    obj.pushKV("mintcapunits_grams", GramsUV((int64_t)HouseMintCapUnits(house)));
    obj.pushKV("capitalcapunits", HouseCapitalCapUnits(house));
    obj.pushKV("reservecapunits", HouseReserveCapUnits(house));
    // The attested ratio and the redemption spread it implies (3.5). Published
    // so a holder can see the cost of the exit BEFORE they take it - the whole
    // deterrent depends on the fee being known ex ante.
    obj.pushKV("attestedratiobps", (uint64_t)HouseAttestedRatioBps(house));
    obj.pushKV("brassagebps", (uint64_t)HouseBrassageBps(house));

    static const auto StatusName = [](char s) -> std::string {
        if (s == HOUSE_STATUS_OPEN) return "open";
        if (s == HOUSE_STATUS_STRESSED) return "stressed";
        if (s == HOUSE_STATUS_DEFERRED) return "deferred";
        if (s == HOUSE_STATUS_INSOLVENT) return "insolvent";
        if (s == HOUSE_STATUS_WOUNDDOWN) return "wounddown";
        return "unknown";
    };
    obj.pushKV("status", StatusName(house.status));
    // The consensus-operative status at the current tip (3.4): stressed /
    // insolvent are usually DERIVED (missed cadence, window expiry), not
    // stored - display must not go stale between transitions and txs.
    {
        const int nTipHeight = chainActive.Height();
        obj.pushKV("effective_status", StatusName(HouseEffectiveStatus(house, nTipHeight)));
        // The merged three-origin derivation (T-b4) - a hand-rolled copy here
        // went stale the moment the protest origin landed.
        const uint32_t nStress = HouseStressOrigin(house, nTipHeight);
        const uint32_t nDeadline = house.nLastAttestHeight + HOUSE_ATTEST_MISS_N * HOUSE_ATTEST_CADENCE;
        if (nStress != 0)
            obj.pushKV("stress_since", (uint64_t)nStress);
        // A protest-stressed house must show its cause: without these a
        // stressed effective_status with healthy attest numbers is opaque.
        // Shown inert too (protest_open 0, heights set): a protest builder
        // needs the raw record for its payload priors (T-b5 inert-at-zero).
        if (house.ProtestLive() || house.nProtestHeight != 0) {
            obj.pushKV("protest_open", (uint64_t)house.nProtestOpen);
            obj.pushKV("protest_height", (uint64_t)house.nProtestHeight);
            obj.pushKV("protest_demand_height", (uint64_t)house.nProtestDemandHeight);
        }
        obj.pushKV("attest_deadline", (uint64_t)nDeadline);
        obj.pushKV("lastattestheight", (uint64_t)house.nLastAttestHeight);
        obj.pushKV("lastattestreserves", ValueFromAmount(house.amountLastAttestReserves));
        obj.pushKV("lastattestreserves_grams", GramsUV((int64_t)house.amountLastAttestReserves));
        // Settlement (Phase 3.7 pt2): the per-house cadence stamp + the derived
        // par-eligibility the clearing board keys its "par lamp" on.
        obj.pushKV("lastsettleheight", (uint64_t)house.nLastSettleHeight);
        obj.pushKV("pareligible", HouseParEligible(house, chainActive.Height()));
        if (house.nInsolventHeight != 0) {
            obj.pushKV("insolventheight", (uint64_t)house.nInsolventHeight);
            obj.pushKV("insolventunits", house.nInsolventUnits);
            obj.pushKV("insolventpot", ValueFromAmount(house.amountInsolventPot));
        }
        obj.pushKV("escrowchangeoutputs", (uint64_t)house.vOutEscrowChange.size());
        obj.pushKV("reservelockoutputs", (uint64_t)house.vOutReserveLock.size());
        // Option-clause state (3.5). The confidence-death counters are
        // published deliberately: CD is a guard, not a kill switch, so the
        // MARKET is what prices a house that keeps reaching for the clause.
        if (house.nDeferInvokedHeight != 0) {
            obj.pushKV("defer_invoked_height", (uint64_t)house.nDeferInvokedHeight);
            obj.pushKV("defer_end_height", (uint64_t)house.DeferEndHeight());
        }
        obj.pushKV("defer_renewals", (uint64_t)house.nDeferRenewals);
        obj.pushKV("defer_activations", (uint64_t)house.nDeferActivations);
        // DR-2: the height the most recent episode ended (recovery), 0 if none.
        // Interest on a demanded note accrues demand -> this height, not to the
        // eventual redemption.
        obj.pushKV("defer_ended_height", (uint64_t)house.nDeferEndedHeight);
        obj.pushKV("defer_suspended_blocks", (uint64_t)house.DeferSuspendedBlocks(nTipHeight));
        obj.pushKV("confidence_dead", HouseConfidenceDead(house, nTipHeight));
    }
    obj.pushKV("registeredheight", (uint64_t)house.nRegisteredHeight);
    obj.pushKV("txidregister", house.txidRegister.ToString());

    UniValue partners(UniValue::VARR);
    for (size_t i = 0; i < house.vPartner.size(); i++) {
        const HousePartner& p = house.vPartner[i];
        UniValue po(UniValue::VOBJ);
        po.pushKV("index", (uint64_t)i);
        po.pushKV("pubkey", HexStr(p.vchPubKey));
        po.pushKV("pledge", ValueFromAmount(p.amountPledge));
        po.pushKV("status", p.status == HOUSE_PARTNER_ACTIVE ? "active"
                          : p.status == HOUSE_PARTNER_SETTLED ? "settled" : "tail");
        if (p.status == HOUSE_PARTNER_TAIL)
            po.pushKV("tailunlockheight", (uint64_t)p.nTailUnlockHeight);
        po.pushKV("pledgeoutputs", (uint64_t)p.vOutPledge.size());
        partners.push_back(po);
    }
    obj.pushKV("partners", partners);
    return obj;
}

UniValue listhouses(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 0)
        throw std::runtime_error(
            "listhouses\n"
            "List all discount houses tracked by the node\n"
            "\nResult (array of house objects)\n"
            "\nExamples:\n"
            + HelpExampleCli("listhouses", "")
            + HelpExampleRpc("listhouses", "")
        );

    LOCK(cs_main);

    UniValue ret(UniValue::VARR);
    for (const CHouse& house : phousetree->GetHouses())
        ret.push_back(HouseToJSON(house));

    return ret;
}

UniValue gethouse(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "gethouse\n"
            "\nArguments:\n"
            "1. id            (numeric, required) the house ID number\n"
            "\nGet one discount house (full record incl. partner set)\n"
            "\nExamples:\n"
            + HelpExampleCli("gethouse", "1")
            + HelpExampleRpc("gethouse", "1")
        );

    const uint32_t nHouseID = request.params[0].get_int();

    LOCK(cs_main);

    CHouse house;
    if (!phousetree->GetHouse(nHouseID, house))
        throw JSONRPCError(RPC_MISC_ERROR, "Unknown house!");

    return HouseToJSON(house);
}

static UniValue PoolToJSON(const CPool& pool)
{
    UniValue obj(UniValue::VOBJ);
    obj.pushKV("pool_id", (uint64_t)pool.nPoolID);
    obj.pushKV("house_id", (uint64_t)pool.nPoolID);   // v1 invariant: one pool per house
    obj.pushKV("fee_bps", (uint64_t)pool.nFeeBps);
    obj.pushKV("note_reserve", pool.nNoteReserve);
    obj.pushKV("note_reserve_grams", GramsUV((int64_t)pool.nNoteReserve));
    obj.pushKV("btx_reserve", pool.amountBtxReserve);
    obj.pushKV("btx_reserve_grams", GramsUV((int64_t)pool.amountBtxReserve));
    obj.pushKV("lp_supply", pool.nLpSupply);
    obj.pushKV("locked_lp", POOL_MIN_LIQUIDITY);
    // Spot price of one note unit in sats, scaled by 1e8 for precision
    // (informational; the executable price includes the fee + impact).
    if (pool.nNoteReserve > 0) {
        const unsigned __int128 px = (unsigned __int128)(uint64_t)pool.amountBtxReserve
                                   * (unsigned __int128)100000000 / (unsigned __int128)pool.nNoteReserve;
        obj.pushKV("spot_price_sats_x1e8", (uint64_t)px);
    }
    obj.pushKV("note_escrow_txid", pool.outNote.hash.ToString());
    obj.pushKV("note_escrow_vout", (uint64_t)pool.outNote.n);
    obj.pushKV("btx_escrow_txid", pool.outBtx.hash.ToString());
    obj.pushKV("btx_escrow_vout", (uint64_t)pool.outBtx.n);
    obj.pushKV("createheight", (uint64_t)pool.nCreateHeight);
    return obj;
}

UniValue listpools(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 0)
        throw std::runtime_error(
            "listpools\n"
            "List all note<->BTX AMM pools tracked by the node\n"
            "\nResult (array of pool objects)\n"
            "\nExamples:\n"
            + HelpExampleCli("listpools", "")
            + HelpExampleRpc("listpools", "")
        );

    LOCK(cs_main);

    UniValue ret(UniValue::VARR);
    for (const CPool& pool : ppooltree->GetPools())
        ret.push_back(PoolToJSON(pool));

    return ret;
}

UniValue getpool(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 1)
        throw std::runtime_error(
            "getpool\n"
            "\nArguments:\n"
            "1. id            (numeric, required) the pool ID (== the house ID)\n"
            "\nGet one AMM pool (reserves, LP supply, fee, custody outpoints)\n"
            "\nExamples:\n"
            + HelpExampleCli("getpool", "1")
            + HelpExampleRpc("getpool", "1")
        );

    const uint32_t nPoolID = request.params[0].get_int();

    LOCK(cs_main);

    CPool pool;
    if (!ppooltree->GetPool(nPoolID, pool))
        throw JSONRPCError(RPC_MISC_ERROR, "Unknown pool!");

    return PoolToJSON(pool);
}

UniValue getgoldfix(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 0)
        throw std::runtime_error(
            "getgoldfix\n"
            "\nThe on-chain gold fix: one shared price, in milligrams of gold\n"
            "per 1000 ECX. Returns null before the first fix has ever formed.\n"
            "\nResult:\n"
            "{\n"
            "  \"raw\":         n,  the median of the last quorum block's submissions\n"
            "  \"braked\":      n,  the damped view: tracks raw up freely, bounded down\n"
            "  \"fixheight\":   n,  height at which this fix formed\n"
            "  \"ageblocks\":   n   tip - fixheight (derived, not stored)\n"
            "}\n"
            "\nConsensus-INERT in this phase: both views are maintained and served,\n"
            "but nothing in the credit rules reads them.\n"
            "\nExamples:\n"
            + HelpExampleCli("getgoldfix", "")
            + HelpExampleRpc("getgoldfix", "")
        );

    LOCK(cs_main);

    CGoldFix fix;
    // No fix yet is a normal state, not an error - the chain runs from genesis
    // with no price until a quorum first forms.
    if (!phousetree->GetGoldFix(fix) || fix.IsNull())
        return NullUniValue;

    UniValue obj(UniValue::VOBJ);
    obj.pushKV("raw", (uint64_t)fix.nRaw);
    obj.pushKV("braked", (uint64_t)fix.nBraked);
    obj.pushKV("fixheight", (uint64_t)fix.nFixHeight);
    const int nTip = chainActive.Height();
    if (nTip >= 0 && (uint32_t)nTip >= fix.nFixHeight)
        obj.pushKV("ageblocks", (uint64_t)((uint32_t)nTip - fix.nFixHeight));
    return obj;
}

UniValue listoraclesubmitters(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 0)
        throw std::runtime_error(
            "listoraclesubmitters\n"
            "\nList the bonded gold-price submitters, with liveness derived from\n"
            "their stored heights (nothing about reliability is stored directly).\n"
            "\nResult (array of):\n"
            "{\n"
            "  \"id\":                n,\n"
            "  \"pubkey\":            \"hex\",\n"
            "  \"bondtxid\":          \"hex\",  the bond escrow coin\n"
            "  \"bondvout\":          n,\n"
            "  \"bondheight\":        n,\n"
            "  \"lastsubmitheight\":  n,   0 = has never submitted\n"
            "  \"blockssincesubmit\": n,   derived; omitted if never\n"
            "  \"unbondrequestheight\": n  0 = none pending\n"
            "}\n"
            "\nHONEST LIMIT: a gap in these heights does NOT prove a submitter was\n"
            "absent. Consensus cannot distinguish \"did not submit\" from \"the block\n"
            "producer did not include it\" - the sequencer authors these records.\n"
            "Do not read this as a reliability score, and note that nothing here\n"
            "may be used to slash: no penalty exists in this phase, and these\n"
            "counters accrued under rules that did not bind.\n"
            "\nExamples:\n"
            + HelpExampleCli("listoraclesubmitters", "")
            + HelpExampleRpc("listoraclesubmitters", "")
        );

    LOCK(cs_main);

    const int nTip = chainActive.Height();
    UniValue ret(UniValue::VARR);
    for (const COracleSubmitter& sub : phousetree->GetOracleSubmitters()) {
        UniValue obj(UniValue::VOBJ);
        obj.pushKV("id", (uint64_t)sub.nSubmitterID);
        obj.pushKV("pubkey", HexStr(sub.vchPubKey));
        // Separate txid/vout, not COutPoint::ToString() - that is a DEBUG form
        // ("COutPoint(61dc76ef37, 0)"): abbreviated hash, unparseable, and
        // useless to any caller wanting to look the coin up.
        obj.pushKV("bondtxid", sub.bondOutpoint.hash.ToString());
        obj.pushKV("bondvout", (uint64_t)sub.bondOutpoint.n);
        obj.pushKV("bondheight", (uint64_t)sub.nBondHeight);
        obj.pushKV("lastsubmitheight", (uint64_t)sub.nLastSubmitHeight);
        if (sub.nLastSubmitHeight != 0 && nTip >= 0 && (uint32_t)nTip >= sub.nLastSubmitHeight)
            obj.pushKV("blockssincesubmit", (uint64_t)((uint32_t)nTip - sub.nLastSubmitHeight));
        obj.pushKV("unbondrequestheight", (uint64_t)sub.nUnbondRequestHeight);
        ret.push_back(obj);
    }
    return ret;
}

UniValue getgramrate(const JSONRPCRequest& request)
{
    if (request.fHelp || request.params.size() != 0)
        throw std::runtime_error(
            "getgramrate\n"
            "Report the launch presentation scale (satoshis per gram of gold).\n"
            "PRESENTATION ONLY: redemption is fixed at par in ECX and this scale\n"
            "is NOT consensus-enforced.\n"
            "\nResult:\n"
            "{\n"
            "  \"sats_per_gram\": n,   (numeric) satoshis representing one gram of gold\n"
            "  \"grams_per_ecx\": n,   (numeric) grams of gold per 1 ECX (1e8 / sats_per_gram)\n"
            "  \"disclaimer\": \"x\"     (string) presentation-scale caveat\n"
            "}\n"
            "\nExamples:\n"
            + HelpExampleCli("getgramrate", "")
            + HelpExampleRpc("getgramrate", "")
        );

    UniValue ret(UniValue::VOBJ);
    ret.pushKV("sats_per_gram", g_launchSatsPerGram);
    ret.pushKV("grams_per_ecx", GramsFromSats(COIN));
    ret.pushKV("disclaimer",
               "launch presentation scale; redemption is fixed ECX; NOT consensus-enforced");
    return ret;
}

static const CRPCCommand commands[] =
{ //  category              name                        actor (function)           argNames
  //  --------------------- ------------------------    -----------------------    ----------
    { "control",            "getmemoryinfo",            &getmemoryinfo,            {"mode"} },
    { "control",            "logging",                  &logging,                  {"include", "exclude"}},
    { "util",               "validateaddress",          &validateaddress,          {"address"} }, /* uses wallet if enabled */
    { "util",               "createmultisig",           &createmultisig,           {"nrequired","keys"} },
    { "util",               "verifymessage",            &verifymessage,            {"address","signature","message"} },
    { "util",               "signmessagewithprivkey",   &signmessagewithprivkey,   {"privkey","message"} },

    /* Not shown in help */
    { "hidden",             "setmocktime",              &setmocktime,              {"timestamp"}},
    { "hidden",             "echo",                     &echo,                     {"arg0","arg1","arg2","arg3","arg4","arg5","arg6","arg7","arg8","arg9"}},
    { "hidden",             "echojson",                 &echo,                     {"arg0","arg1","arg2","arg3","arg4","arg5","arg6","arg7","arg8","arg9"}},
    { "hidden",             "getinfo",                  &getinfo_deprecated,       {}},

    /* Sidechain RPC functions */
    { "sidechain",          "refreshbmm",                   &refreshbmm,                    {"amount", "createnew", "prevblock"}},
    { "sidechain",          "get_block_template",           &get_block_template,            {}},
    { "sidechain",          "connect_block",                &connect_block,                 {"block", "main_block_hash"}},
    { "sidechain",          "get_bmm_inclusions",           &get_bmm_inclusions,            {"critical_hash"}},
    { "sidechain",          "setcoinbasetag",               &setcoinbasetag,                {"name"}},
    { "sidechain",          "getaveragemainchainfees",      &getaveragemainchainfees,       {"blockcount", "startheight"}},
    { "sidechain",          "getmainchainblockcount",       &getmainchainblockcount,        {}},
    { "sidechain",          "getmainchainblockhash",        &getmainchainblockhash,         {"height"}},
    { "sidechain",          "getwithdrawalbundle",          &getwithdrawalbundle,           {}},
    { "sidechain",          "verifymainblockcache",         &verifymainblockcache,          {}},
    { "sidechain",          "updatemainblockcache",         &updatemainblockcache,          {}},
    { "sidechain",          "listmywithdrawals",            &listmywithdrawals,             {}},
    { "sidechain",          "rebroadcastwithdrawalbundle",  &rebroadcastwithdrawalbundle,   {}},
    { "sidechain",          "getwithdrawal",                &getwithdrawal,                 {"id"}},
    { "sidechain",          "formatdepositaddress",         &formatdepositaddress,          {"address"}},

    { "bills",              "listbills",                    &listbills,                     {}},
    { "bills",              "getbill",                      &getbill,                       {"id"}},
    { "bills",              "listloanbook",                 &listloanbook,                  {"house_id"}},

    { "houses",             "listhouses",                   &listhouses,                    {}},
    { "houses",             "gethouse",                     &gethouse,                      {"id"}},

    { "pools",              "listpools",                    &listpools,                     {}},
    { "pools",              "getpool",                      &getpool,                       {"id"}},

    { "freebank",           "getgramrate",                  &getgramrate,                   {}},

    { "oracle",             "getgoldfix",                   &getgoldfix,                    {}},
    { "oracle",             "listoraclesubmitters",         &listoraclesubmitters,          {}},

    /* BitAssets */
    { "BitAssets",          "listassets",                   &listassets,                    {}},
};

void RegisterMiscRPCCommands(CRPCTable &t)
{
    for (unsigned int vcidx = 0; vcidx < ARRAYLEN(commands); vcidx++)
        t.appendCommand(commands[vcidx].name, &commands[vcidx]);
}
