#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    // seed.ecxfreebank.com (68.183.235.153:8455) — the live FreeBank seed on eCash alpha.
    // Replaces two dead CryptAxe signet leftovers (…:2599) that never answered. The DNS
    // seed above is the primary discovery path; this is the hardcoded fallback.
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x44,0xb7,0xeb,0x99}, 8455}
};

#endif // BITCOIN_CHAINPARAMSSEEDS_H
